RentACar/Controllers/AppealsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentACar.Data;
using RentACar.Models;

namespace RentACar.Controllers
{
    public class AppealsController : Controller
    {
        private readonly RentContext _context;

        public AppealsController(RentContext context)
        {
            _context = context;
        }

        // GET: Appeals
        public async Task<IActionResult> ViewAll()
        {
            return View(await _context.Appeales.ToListAsync());
        }

        // GET: Appeals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appeal = await _context.Appeales
                .FirstOrDefaultAsync(m => m.ID == id);
            if (appeal == null)
            {
                return NotFound();
            }

            return View(appeal);
        }

        // GET: Appeals/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Appeals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Contact,Text")] Appeal appeal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(appeal);
                await _context.SaveChangesAsync();
                return Redirect("~/Home/IndexNew");
            }
            return View(appeal);
        }

        // GET: Appeals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appeal = await _context.Appeales.FindAsync(id);
            if (appeal == null)
            {
                return NotFound();
            }
            return View(appeal);
        }

        // POST: Appeals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Contact,Text")] Appeal appeal)
        {
            if (id != appeal.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appeal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppealExists(appeal.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ViewAll));
            }
            return View(appeal);
        }

        // GET: Appeals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appeal = await _context.Appeales
                .FirstOrDefaultAsync(m => m.ID == id);
            if (appeal == null)
            {
                return NotFound();
            }

            return View(appeal);
        }

        // POST: Appeals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appeal = await _context.Appeales.FindAsync(id);
            _context.Appeales.Remove(appeal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ViewAll));
        }

        private bool AppealExists(int id)
        {
            return _context.Appeales.Any(e => e.ID == id);
        }
    }
}

RentACar/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RentACar.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using RentACar.Data;
using System.IO;
using Microsoft.EntityFrameworkCore;

namespace RentACar.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly RentContext _context;

        public HomeController(ILogger<HomeController> logger, RentContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> IndexNew()
        {
            return View(await _context.Cars.Take(4).Include(p => p.Pictures).ToListAsync());
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult AboutUS()
        {
            return View();
        }
        public IActionResult Transfer()
        {
            return View();
        }
        public IActionResult GetContact()
        {
            var filepath = Path.Combine("~\\files", "contact.txt");
            return File(filepath, "text/plain", "contact.txt");

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult InitialBase()
        {
            if (_context.Cars.Any() || _context.Drivers.Any())
            {
                return Redirect("/Home/Index/");
            }
            var Cars = new List<Car>
            {
            new Car{Manufacturer="Ford",Model="Focus",Year=2020,WheelDrive="front",VechicleVolume=1.6,CarType="sedan",Odometer=768,MaxMileageatDay=100,Price=3000,OverPrice=5000,Deposit=10000,InUse=false,InRepair=false,FuelMax=50,CurrentFuel=30,FuelRate=5 },

            new Car{Manufacturer="Reno",Model="Duster",Year=2018,WheelDrive="full",VechicleVolume=2.0,CarType="hachback",Odometer=3768,MaxMileageatDay=100,Price=4000,OverPrice=5000,Deposit=10000,InUse=false,InRepair=false,FuelMax=50,CurrentFuel=30,FuelRate=8 },

            new Car{Manufacturer="Opel",Model="Astra",Year=2017,WheelDrive="front",VechicleVolume=2.0,CarType="sedan",Odometer=6768,MaxMileageatDay=100,Price=3500,OverPrice=5000,Deposit=10000,InUse=false,InRepair=false,FuelMax=50,CurrentFuel=20,FuelRate=7 },

            new Car{Manufacturer="Kia",Model="Optima",Year=2020,WheelDrive="full",VechicleVolume=2.0,CarType="sedan",Odometer=2000,MaxMileageatDay=100,Price=5000,OverPrice=5000,Deposit=10000,InUse=false,InRepair=false,FuelMax=50,CurrentFuel=25,FuelRate=12 },

            };
            Cars.ForEach(s => _context.Cars.Add(s));
            _context.SaveChanges();

            var Drivers = new List<Driver>
            {
            new Driver{FName="Alex",LName="Ivanov", BirthdayDate=DateTime.Parse("1989-05-05"),PhoneNumber="8-900-555-2020",Passport="2809-546237", AddDate=DateTime.Now,Email="1@1.ru",DriveLicense="99 45 213432"},
            new Driver{FName="Olga",LName="Petrova", BirthdayDate=DateTime.Parse("1993-10-05"),PhoneNumber="8-900-555-1000",Passport="2809-343337", AddDate=DateTime.Now,Email="2@1.ru",DriveLicense="99 45 213432"},
            new Driver{FName="Fu",LName="Kim", BirthdayDate=DateTime.Parse("1998-10-10"),PhoneNumber="8-900-555-6767",Passport="2809-234322", AddDate=DateTime.Now,Email="3@1.ru",DriveLicense="99 45 213432"},
            new Driver{FName="Vasil",LName="Johnson", BirthdayDate=DateTime.Parse("2001-12-12"),PhoneNumber="8-900-555-2666",Passport="2809-34333", AddDate=DateTime.Now,Email="4@1.ru",DriveLicense="99 45 213432" }
            };

            Drivers.ForEach(s => _context.Drivers.Add(s));
            _context.SaveChanges();

            return Redirect("/Home/Index/");
        }
    }
}

RentACar/Views/Home/AboutUS.cshtml
@model RentACar.Models.Appeal
<body>
    <div class="container">
        <hr>
        <div class="row">
            <div class="col-6">
                <h1>Alexey Martynov</h1>
            </div>
            <div class="col-6">
                <a asp-controller="Home" asp-action="GetContact">Get Contact</a>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <div class="media">
                    <img class="mr-3" src="~/images/115X115.gif" alt="Generic placeholder image">
                    <div class="media-body">
                        <h5 class="mt-0">Web Developer</h5>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="row justify-content-md-around m-1">
                    <address>
                        <strong>John Doe</strong><br>
                        1355 Market St, Suite 900<br>
                        San Francisco, CA 94103<br>
                        <abbr title="Phone">P:</abbr> (123) 456-7890<br>
                        <a href="mailto:#">first.last@example.com</a>
                    </address>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-6 col-sm-12">
                <h2>Education</h2>
                <hr>
                <div class="row">
                    <div class="col-6">
                        <h4>College of Web Design</h4>
                    </div>
                    <div class="col-6">
                        <h5 class="text-right"><span aria-hidden="true"></span> Jan 2014 - Dec 2016</h5>
                    </div>
                </div>
                <h5><span class="badge badge-secondary">Bachelors</span></h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, recusandae, corporis, tempore nam fugit deleniti sequi excepturi quod repellat laboriosam soluta laudantium amet dicta non ratione distinctio nihil dignissimos esse!</p>
                <div class="row">
                    <div class="col-6">
                        <h4>University of Web Design</h4>
                    </div>
                    <div class="col-6">
                        <h5 class="text-right"><span aria-hidden="true"></span> Jan 2016 - Dec 2020</h5>
                    </div>
                </div>
                <h5><span class="badge badge-secondary">Masters</span></h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, recusandae, corporis, tempore nam fugit deleniti sequi excepturi quod repellat laboriosam soluta laudantium amet dicta non ratione distinctio nihil dignissimos esse!</p>
            </div>
            <div class="col-md-6 col-sm-12">
                <h2>Skill Set</h2>
                <hr>
                <div class="progress mt-4">
                    <div class="progress-bar bg-success" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 85%"> HTML</div>
                </div>
                <div class="progress mt-4">
                    <div class="progress-bar bg-success" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%"> CSS</div>
                </div>
                <div class="progress mt-4">
                    <div class="progress-bar bg-success" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%"> JAVASCRIPT</div>
                </div>
                <div class="progress mt-4">
                    <div class="progress-bar bg-info" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 90%"> C#</div>
                </div>
                <div class="progress mt-4">
                    <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100" style="width: 55%"> WORDPRESS</div>
                </div>
                <div class="progress mt-4">
                    <div class="progress-bar bg-danger" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%"> PHOTOSHOP</div>
                </div>
                <div class="progress mt-4">
                    <div class="progress-bar bg-danger" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%"> ILLUSTRATOR</div>
                </div>
            </div>
        </div>
        <hr>
        <h2>Work Experience</h2>
        <hr>
        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="row">
                    <div class="col-5">
                        <h4>ABC Corp.</h4>
                    </div>
                    <div class="col-6">
                        <h5 class="text-right"><span aria-hidden="true"></span> Jan 2012 - Dec 2016</h5>
                    </div>
                </div>
                <h5><span class="badge badge-secondary">Web Developer</span></h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, recusandae, corporis, tempore nam fugit deleniti sequi excepturi quod repellat laboriosam soluta laudantium amet dicta non ratione distinctio nihil dignissimos esse!</p>
                <ul>
                    <li>Lorem ipsum dolor sit amet.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipisicing.</li>
                </ul>
            </div>
            <div class="col-md-6 col-sm-12">
                <div class="row">
                    <div class="col-5">
                        <h4>XYZ Corp.</h4>
                    </div>
                    <div class="col-6">
                        <h5 class="text-right"><span aria-hidden="true"></span> Jan 2016 - Dec 2020</h5>
                    </div>
                </div>
                <h5><span class="badge badge-secondary">Senior Web Developer</span></h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, recusandae, corporis, tempore nam fugit deleniti sequi excepturi quod repellat laboriosam soluta laudantium amet dicta non ratione distinctio nihil dignissimos esse!</p>
                <ul>
                    <li>Lorem ipsum dolor sit amet.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipisicing.</li>
                </ul>
            </div>
        </div>
        <hr>
        <h2>Portfolio</h2>
        <hr>
        <div class="container">
            <div class="row text-center">
                <div class="col-sm-4 col-12 p-0"><img class="img-thumbnail" src="~/images/300X200.gif" alt=""></div>
                <div class="col-sm-4 col-12 p-0"><img class="img-thumbnail" src="~/images/300X200.gif" alt=""></div>
                <div class="col-sm-4 col-12 p-0"><img class="img-thumbnail" src="~/images/300X200.gif" alt=""></div>
            </div>
            <div class="row text-center">
                <div class="col-sm-4 col-12 p-0"><img class="img-thumbnail" src="~/images/300X200.gif" alt=""></div>
                <div class="col-sm-4 col-12 p-0"><img class="img-thumbnail" src="~/images/300X200.gif" alt=""></div>
                <div class="col-sm-4 col-12 p-0"><img class="img-thumbnail" src="~/images/300X200.gif" alt=""></div>
            </div>
        </div>
        <hr>
        <h2>Contact</h2>
        <hr>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8  col-12 jumbotron">
                    <form asp-controller="Appeals" asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name">Ваше Имя</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Укажите ваше имя" required>
                        </div>
                        <div class="form-group">
                            <label asp-for="Contact">Способ связи</label>
                            <input type="text" class="form-control" id="contact" name="contact" placeholder="Укажите вашу почту или телефон" aria-describedby="text"required>
                        </div>
                        <div class="form-group">
                            <label asp-for="Text">Текст Обращения</label>
                            <span asp-validation-for="Text" class="text-danger"></span>
                            <textarea rows="10" cols="100" class="form-control" id="Text" name="Text" placeholder="Введите ваше сообщение" aria-describedby="messageHelp"required></textarea>
                            <span id="messageHelp" class="form-text text-muted" style="display: none;">Введите ваше сообщение</span>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Отправить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RentACar/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Добро пожаловать в авто прокат</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div class="col-lg-4 col-md-6 col-22">
    <ul class="list-unstyled">
        <li class="media">
            <div class="media-body">
                <h5 class="mt-0 mb-1">Fast start</h5>
                <p class="mb-0">Add Entities to BD for test app</p>
                <a class="btn btn-danger" asp-area="" asp-controller="Home" asp-action="InitialBase">AddTestItem</a>
            </div>
        </li>
    </ul>
</div>

RentACar/Views/Home/Transfer.cshtml
<div class="container">
    <div class="row">
        <div class="col-lg-12 mb-4 mt-2 text-center">
            <h2>Услуги трансфера</h2>
        </div>
    </div>
</div>
<div class="container ">
    <h3>В Аэропорты Москвы</h3>
    <div class="row">
        <div class="col-lg-3 col-md-6 col-sm-12 text-center">
            <img class="rounded-circle" alt="140x140" style="width: 140px; height: 140px;" src="~/images/140X140.gif" data-holder-rendered="true">
            <h3>Домодедово</h3>
            <p>Быстрой и комфортный трансфер</p>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 text-center">
            <img class="rounded-circle" alt="140x140" style="width: 140px; height: 140px;" src="~/images/140X140.gif" data-holder-rendered="true">
            <h3>Внуково</h3>
            <p>Быстрой и комфортный трансфер.</p>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 text-center">
            <img class="rounded-circle" alt="140x140" style="width: 140px; height: 140px;" src="~/images/140X140.gif" data-holder-rendered="true">
            <h3>Шереметьево</h3>
            <p>Быстрой и комфортный трансфер</p>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 text-center">
            <img class="rounded-circle" alt="140x140" style="width: 140px; height: 140px;" src="~/images/140X140.gif" data-holder-rendered="true">
            <h3>Жуковский</h3>
            <p>Быстрой и комфортный трансфер</p>
        </div>
    </div>
        <h3>В Аэропорты Санкт петербурга</h3>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 text-center">
                <img class="rounded-circle" alt="140x140" style="width: 140px; height: 140px;" src="~/images/140X140.gif" data-holder-rendered="true">
                <h3>Пулково</h3>
                <p>Быстрой и комфортный трансфер</p>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 text-center">
                <img class="rounded-circle" alt="140x140" style="width: 140px; height: 140px;" src="~/images/140X140.gif" data-holder-rendered="true">
                <h3>Аэропорт Хельсинки</h3>
                <p>Быстрой и комфортный трансфер</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 mt-4 mb-2 text-center">
                <h2>Трансфер по России</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-lg-6">
                <blockquote class="blockquote">
                    <p class="mb-0">Отвезем из любой точки по России</p>
                    <small class="blockquote-footer">по предварительному заказу</small>
                </blockquote>
            </div>
            <div class="col-sm-6 col-lg-6">
                <blockquote class="blockquote">
                    <p class="mb-0">Привезем в любую точку в России</p>
                    <small class="blockquote-footer">по предварительному заказу</small>
                </blockquote>
            </div>
        </div>
    </div>
<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="text-center col-md-8 col-12 mx-auto">
                <p class="lead">Нужен трансфер?</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 col-auto mx-auto"> <a class="btn btn-block btn-lg btn-success" asp-controller="Appeals" asp-action="Create">Заказать!</a> </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12 mb-2 text-center">
            <h2>Наши Сервисы</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-lg-4">
            <h3>Аренда</h3>
            <p> Предоставляем услуги аренды авто </p>
            <p><a class="btn btn-link" asp-controller="Home" asp-action="AboutUS">View details »</a></p>
        </div>
        <div class="col-sm-6 col-lg-4">
            <h3>Лизинг</h3>
            <p> Предоставляем услуги лизинга авто </p>
            <p><a class="btn btn-link" asp-controller="Home" asp-action="AboutUS">View details »</a></p>
        </div>
        <div class="col-sm-6 col-lg-4">
            <h3>Трансфер</h3>
            <p> Предоставляем услуги трансфера</p>
            <p><a class="btn btn-link" asp-controller="Home" asp-action="AboutUS">View details »</a></p>
        </div>        
    </div>
</div>