RentACar/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentACar.Data;
using RentACar.Models;

namespace RentACar.Controllers
{
    public class CarsController : Controller
    {
        private readonly RentContext _context;
        private bool Admin => HttpContext.User.HasClaim("Admin", bool.TrueString);

        public CarsController(RentContext context)
        {
            _context = context;
        }

        // GET: Cars
        public async Task<IActionResult> Index()
        {

            return View(await _context.Cars.Include(p => p.Pictures).ToListAsync());
        }
        public async Task<IActionResult> AdminPage()
        {
            if (!Admin) return Forbid();
            return View(await _context.Cars.ToListAsync());
        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .FirstOrDefaultAsync(m => m.ID == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Cars/Create
        public IActionResult Create()
        {
            if (!Admin) return Forbid();
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Manufacturer,Model,Year,Vechicle,VechicleVolume,WheelDrive,CarType,Odometer,MaxMileageatDay,Price,OverPrice,Deposit,RegistrationNumber,IdentificationNumber,VinNumber,InsuranceNumber,Color,InUse,InRepair,FuelMax,CurrentFuel,FuelRate,ShortDescription")] Car car)
        {
            if (ModelState.IsValid)
            {
                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)return NotFound();
            if (!Admin) return Forbid();


            var car = await _context.Cars.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Manufacturer,Model,Year,Vechicle,WheelDrive,CarType,VechicleVolume,Odometer,MaxMileageatDay,Price,OverPrice,Deposit,RegistrationNumber,IdentificationNumber,VinNumber,InsuranceNumber,Color,InUse,InRepair,FuelMax,CurrentFuel,FuelRate,ShortDescription")] Car car)
        {
            if (id != car.ID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            if (!Admin) return Forbid();

            var car = await _context.Cars
                .FirstOrDefaultAsync(m => m.ID == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _context.Cars.FindAsync(id);
            var pictures =  _context.Pictures.Where(x=>x.CarID==id);
            foreach(var pic in pictures)
            {
                _context.Pictures.Remove(pic);
            }
            _context.Cars.Remove(car);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
            return _context.Cars.Any(e => e.ID == id);
        }
    }
}

RentACar/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentACar.Data;
using RentACar.Models;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;

namespace RentACar.Controllers
{ 
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly RentContext _context;
        private bool Admin => HttpContext.User.HasClaim("Admin", bool.TrueString);
        public OrdersController(RentContext context)
        {
            _context = context;
        }

        // GET: All Orders
        public async Task<IActionResult> Index()
        {
            if (!Admin) return Forbid();

            var rentContext = _context.Orders.Include(o => o.Car).Include(o => o.Driver);
            return View(await rentContext.ToListAsync());
        }
        // GET: Orders in work
        public async Task<IActionResult> InWork()
        {
            if (!Admin) return Forbid();

            var rentContext = _context.Orders.Include(o => o.Car).Include(o => o.Driver).Where(x => x.Closed != true);
            return View(await rentContext.ToListAsync());
        }
        // GET: Closed Orders
        public async Task<IActionResult> Closed()
        {
            if (!Admin) return Forbid();

            var rentContext = _context.Orders.Include(o => o.Car).Include(o => o.Driver).Where(x => x.Closed == true);
            return View(await rentContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!Admin) return Forbid();
            if (id == null)return NotFound();

            var order = await _context.Orders
                .Include(o => o.Car)
                .Include(o => o.Driver)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            if (!Admin) return Forbid();
            ViewData["CarID"] = new SelectList(_context.Cars.Where(x=>x.InUse!=true&&x.InRepair!=true), "ID", "FullName");
            ViewData["DriverID"] = new SelectList(_context.Drivers, "ID", "FullName");

            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderID,CarID,DriverID,OrderDate,OdometerStart,FuelStart")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                var car = await _context.Cars.FindAsync(order.CarID);
                car.InUse = true;
                _context.Update(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarID"] = new SelectList(_context.Cars, "ID", "ID", order.CarID);
            ViewData["DriverID"] = new SelectList(_context.Drivers, "ID", "FName", order.DriverID);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!Admin) return Forbid();
            if (id == null) return NotFound();

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["CarID"] = new SelectList(_context.Cars, "ID", "ID", order.CarID);
            ViewData["DriverID"] = new SelectList(_context.Drivers, "ID", "FName", order.DriverID);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderID,CarID,DriverID,OrderDate,OdometerStart,FuelStart,OrderReturnDate,OdometerFinish,FuelFinish,NumberofDays,ExtraMileage,Price")] Order order)
        {
            if (id != order.OrderID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarID"] = new SelectList(_context.Cars, "ID", "ID", order.CarID);
            ViewData["DriverID"] = new SelectList(_context.Drivers, "ID", "FName", order.DriverID);
            return View(order);
        }
        public async Task<IActionResult> CloseOrder(int? id)
        {
            if (!Admin)return Forbid();
            if (id == null)return NotFound();

            ViewData["CarID"] = new SelectList(_context.Cars, "ID", "FullName");
            ViewData["DriverID"] = new SelectList(_context.Drivers, "ID", "FullName");

            var order = await _context.Orders.Include(x => x.Car).Include(x => x.Driver).FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null) return NotFound();
            return View(order);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CloseOrder([Bind("OrderID,CarID,DriverID,OrderDate,OdometerStart,FuelStart,OrderReturnDate,OdometerFinish,FuelFinish")] Order order)
        {
            if (ModelState.IsValid)
            {
                order.Closed = true;
                order.Price = 0;
                order.ExtraMileage = 0;
                order.MaxMileage = 0;
                var car = await _context.Cars.FindAsync(order.CarID);
                var mileage = order.OdometerFinish - order.OdometerStart;
                var days =(DateTime)order.OrderReturnDate-order.OrderDate;
                
                if (days.Days >= 0) order.NumberofDays = days.Days;
                if (order.NumberofDays == 0) { order.NumberofDays = 1; }

                order.MaxMileage = order.NumberofDays * car.MaxMileageatDay;
                if (mileage > order.MaxMileage) {
                    order.ExtraMileage = mileage - order.MaxMileage;
                    if (order.ExtraMileage % 100 == 0)
                    {
                        order.Price += car.OverPrice * order.ExtraMileage / 100;
                    }
                    else order.Price += car.OverPrice * (order.ExtraMileage / 100+1);
                }
                
                order.Price += car.Price * order.NumberofDays;
                if(order.FuelFinish<order.FuelStart)
                {
                    var extrafuel = order.FuelStart - order.FuelFinish;
                    order.Price += Convert.ToInt32(extrafuel * 50);
                }
                _context.Update(order);
                car.InUse = false;               
                var driver = await _context.Drivers.FindAsync(order.DriverID);
                if (mileage != null && mileage > 0) { driver.Mileage += (int)mileage; car.Odometer += (int)mileage; }
                _context.Update(driver);
                _context.Update(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        public async Task<IActionResult> PayInfo(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Car)
                .Include(o => o.Driver)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }
        public async Task<IActionResult> GetPay(int? id)
        {
            Pay pay = new Pay();

            var order = await _context.Orders
                .Include(o => o.Car)
                .Include(o => o.Driver)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            pay.Date = order.OrderDate;
            pay.Model = order.Car.FullName;
            pay.Name = order.Driver.FullName;
            pay.Price = (int)order.Price;

            System.Xml.Serialization.XmlSerializer xml = new System.Xml.Serialization.XmlSerializer(typeof(Pay));
            var stream = new System.IO.MemoryStream();
            xml.Serialize(stream, pay);
            stream.Flush();
            var data = stream.GetBuffer();
            stream.Close();
            string name = order.OrderDate.Date.Month.ToString()+" "+order.OrderDate.Date.Day.ToString()+"_"+ order.OrderID;
            return File(data, "application/xhtml+xml", name+".xml");
        }
        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!Admin) return Forbid();
            if (id == null) return NotFound();

            var order = await _context.Orders
                .Include(o => o.Car)
                .Include(o => o.Driver)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)

RentACar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RentACar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RentACar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">Автомобили</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Drivers" asp-action="Index">Водители</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Заказы</a>
                            </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - RentACar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

RentACar/Views/Shared/_LayoutNew.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome to RentACar</title>
    <!-- Bootstrap -->
    <link href="~/css/bootstrap-4.4.1.css" rel="stylesheet">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="IndexNew">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                @if (User.HasClaim("Admin", bool.TrueString))
                {
                    <li class="nav-item">
                        <a class="nav-link aria-haspopup text-white" asp-area="" asp-controller="Cars" asp-action="AdminPage">Автомобили</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link aria-haspopup text-white" asp-area="" asp-controller="Drivers" asp-action="Index">Водители</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link aria-haspopup text-success" asp-area="" asp-controller="Orders" asp-action="Create">Новый заказ</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Заказы</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="Orders" asp-action="InWork">В работе</a>
                            <a class="dropdown-item" asp-controller="Orders" asp-action="Closed">Закрытые</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Orders" asp-action="Index">Посмотреть Все</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Онлайн заказы</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item text-success" asp-controller="Feedbacks" asp-action="New">Новые</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Feedbacks" asp-action="Index">Посмотреть Все</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link aria-haspopup text-success" asp-area="" asp-controller="Appeals" asp-action="ViewAll">Обращения</a>
                    </li>

                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Cars" asp-action="Index">Прокат</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Transfer">Трансфер</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Cars" asp-action="Index">Лизинг</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="AboutUS">О нас</a>
                    </li>
                }

            </ul>

            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <partial name="_LoginPartial" />
        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - RentACar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>