RentACar/Models/Car.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace RentACar.Models
{
    public class Car
    {
        public int ID { get; set; }

        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public string Vechicle { get; set; }
        [Required(ErrorMessage = "Поле не может быть пустым")]
        [RegularExpression(@"^[0-9]*[,]?[0-9]+$", ErrorMessage = "Числа вводятся в формате x или x,x")]
        public double VechicleVolume { get; set; }
        public string WheelDrive { get; set; }
        public string CarType { get; set; }
        public int Odometer { get; set; }
        public int MaxMileageatDay { get; set; }
        public int Price { get; set; }
        public int OverPrice { get; set; }
        public int Deposit { get; set; }
        public string RegistrationNumber { get; set; }
        public string IdentificationNumber { get; set; }
        public string VinNumber { get; set; }
        public string InsuranceNumber { get; set; }
        public string Color { get; set; }
        public bool InUse { get; set; }
        public bool InRepair { get; set; }
        public double FuelMax { get; set; }
        public double CurrentFuel { get; set; }
        public double FuelRate { get; set; }
        public string ShortDescription { get; set; }

        public List<PictureModel> Pictures { get; set; } = new List<PictureModel>();

        public ICollection<Order> Order { get; set; }
        public string FullName
        {
            get
            {
                return ID + "--" + Manufacturer + "--" + Model+"--"+Year;
            }
        }
        public string TradeNameYear
        {
            get
            {
                return Manufacturer + "-" + Model + "-" + Year;
            }
        }
        public string TradeName
        {
            get
            {
                return Manufacturer + "-" + Model;
            }
        }



    }
}

RentACar/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentACar.Data;
using RentACar.Models;

namespace RentACar.Controllers
{
    public class CarsController : Controller
    {
        private readonly RentContext _context;
        private bool Admin => HttpContext.User.HasClaim("Admin", bool.TrueString);

        public CarsController(RentContext context)
        {
            _context = context;
        }

        // GET: Cars
        public async Task<IActionResult> Index()
        {

            return View(await _context.Cars.Include(p => p.Pictures).ToListAsync());
        }
        public async Task<IActionResult> AdminPage()
        {
            if (!Admin) return Forbid();
            return View(await _context.Cars.ToListAsync());
        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .FirstOrDefaultAsync(m => m.ID == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Cars/Create
        public IActionResult Create()
        {
            if (!Admin) return Forbid();
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Manufacturer,Model,Year,Vechicle,VechicleVolume,WheelDrive,CarType,Odometer,MaxMileageatDay,Price,OverPrice,Deposit,RegistrationNumber,IdentificationNumber,VinNumber,InsuranceNumber,Color,InUse,InRepair,FuelMax,CurrentFuel,FuelRate,ShortDescription")] Car car)
        {
            if (ModelState.IsValid)
            {
                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)return NotFound();
            if (!Admin) return Forbid();


            var car = await _context.Cars.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Manufacturer,Model,Year,Vechicle,WheelDrive,CarType,VechicleVolume,Odometer,MaxMileageatDay,Price,OverPrice,Deposit,RegistrationNumber,IdentificationNumber,VinNumber,InsuranceNumber,Color,InUse,InRepair,FuelMax,CurrentFuel,FuelRate,ShortDescription")] Car car)
        {
            if (id != car.ID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            if (!Admin) return Forbid();

            var car = await _context.Cars
                .FirstOrDefaultAsync(m => m.ID == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _context.Cars.FindAsync(id);
            var pictures =  _context.Pictures.Where(x=>x.CarID==id);
            foreach(var pic in pictures)
            {
                _context.Pictures.Remove(pic);
            }
            _context.Cars.Remove(car);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
            return _context.Cars.Any(e => e.ID == id);
        }
    }
}

RentACar/Controllers/PictureModelsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentACar.Data;
using RentACar.Models;
using Microsoft.AspNetCore.Hosting;

namespace RentACar.Controllers
{
    public class PictureModelsController : Controller
    {
        private readonly RentContext _context;
        private IWebHostEnvironment _environment;

        public PictureModelsController(RentContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        // GET: PictureModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pictures.ToListAsync());
        }

        public async Task<IActionResult> AddFile(IFormFile uploadedFile)
        {
            if (uploadedFile != null)
            {
                string path = "/Files/" + uploadedFile.FileName;
                using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }
                PictureModel picture = new PictureModel { Name = uploadedFile.FileName, Path = path };
                _context.Pictures.Add(picture);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> AddPictureToCar(int? id, IFormFile uploadedFile)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (uploadedFile != null)
            {
                string path = "/Files/" + uploadedFile.FileName;
                using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }
                PictureModel picture = new PictureModel { Name = uploadedFile.FileName, Path = path };
                var car = await _context.Cars
                .FirstOrDefaultAsync(b => b.ID == id);
                car.Pictures.Add(picture);
                _context.Cars.Update(car);
                _context.SaveChanges();
            }
            return Redirect(("/Cars/Details/" + id.ToString()));
        }
        // GET: PictureModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pictureModel = await _context.Pictures
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pictureModel == null)
            {
                return NotFound();
            }

            return View(pictureModel);
        }

        // GET: PictureModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PictureModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Path")] PictureModel pictureModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pictureModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pictureModel);
        }

        // GET: PictureModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pictureModel = await _context.Pictures.FindAsync(id);
            if (pictureModel == null)
            {
                return NotFound();
            }
            return View(pictureModel);
        }

        // POST: PictureModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Path")] PictureModel pictureModel)
        {
            if (id != pictureModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pictureModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PictureModelExists(pictureModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pictureModel);
        }

        // GET: PictureModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pictureModel = await _context.Pictures
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pictureModel == null)
            {
                return NotFound();
            }

            return View(pictureModel);
        }

        // POST: PictureModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pictureModel = await _context.Pictures.FindAsync(id);
            _context.Pictures.Remove(pictureModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PictureModelExists(int id)
        {
            return _context.Pictures.Any(e => e.Id == id);
        }
    }
}

RentACar/Views/Cars/AdminPage.cshtml
@model IEnumerable<RentACar.Models.Car>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Manufacturer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vechicle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VechicleVolume)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WheelDrive)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Odometer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxMileageatDay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OverPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deposit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegistrationNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdentificationNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VinNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InsuranceNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InUse)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InRepair)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FuelMax)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrentFuel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FuelRate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Manufacturer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vechicle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VechicleVolume)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WheelDrive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Odometer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxMileageatDay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OverPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deposit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegistrationNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdentificationNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VinNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InsuranceNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InUse)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InRepair)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FuelMax)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrentFuel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FuelRate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

RentACar/Views/Cars/Create.cshtml
@model RentACar.Models.Car

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Manufacturer" class="control-label"></label>
                <input asp-for="Manufacturer" class="form-control" />
                <span asp-validation-for="Manufacturer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vechicle" class="control-label"></label>
                <input asp-for="Vechicle" class="form-control" />
                <span asp-validation-for="Vechicle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VechicleVolume" class="control-label"></label>
                <input asp-for="VechicleVolume" class="form-control" />
                <span asp-validation-for="VechicleVolume" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WheelDrive" class="control-label"></label>
                <input asp-for="WheelDrive" class="form-control" />
                <span asp-validation-for="WheelDrive" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarType" class="control-label"></label>
                <input asp-for="CarType" class="form-control" />
                <span asp-validation-for="CarType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Odometer" class="control-label"></label>
                <input asp-for="Odometer" class="form-control" />
                <span asp-validation-for="Odometer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxMileageatDay" class="control-label"></label>
                <input asp-for="MaxMileageatDay" class="form-control" />
                <span asp-validation-for="MaxMileageatDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OverPrice" class="control-label"></label>
                <input asp-for="OverPrice" class="form-control" />
                <span asp-validation-for="OverPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deposit" class="control-label"></label>
                <input asp-for="Deposit" class="form-control" />
                <span asp-validation-for="Deposit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegistrationNumber" class="control-label"></label>
                <input asp-for="RegistrationNumber" class="form-control" />
                <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdentificationNumber" class="control-label"></label>
                <input asp-for="IdentificationNumber" class="form-control" />
                <span asp-validation-for="IdentificationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VinNumber" class="control-label"></label>
                <input asp-for="VinNumber" class="form-control" />
                <span asp-validation-for="VinNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InsuranceNumber" class="control-label"></label>
                <input asp-for="InsuranceNumber" class="form-control" />
                <span asp-validation-for="InsuranceNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="InUse" /> @Html.DisplayNameFor(model => model.InUse)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="InRepair" /> @Html.DisplayNameFor(model => model.InRepair)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="FuelMax" class="control-label"></label>
                <input asp-for="FuelMax" class="form-control" />
                <span asp-validation-for="FuelMax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CurrentFuel" class="control-label"></label>
                <input asp-for="CurrentFuel" class="form-control" />
                <span asp-validation-for="CurrentFuel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FuelRate" class="control-label"></label>
                <input asp-for="FuelRate" class="form-control" />
                <span asp-validation-for="FuelRate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RentACar/Views/Cars/Details.cshtml
@model RentACar.Models.Car

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vechicle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vechicle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VechicleVolume)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VechicleVolume)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WheelDrive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WheelDrive)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Odometer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Odometer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaxMileageatDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaxMileageatDay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OverPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OverPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deposit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deposit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentificationNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdentificationNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VinNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VinNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InsuranceNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InsuranceNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InUse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InUse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InRepair)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InRepair)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FuelMax)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FuelMax)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentFuel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CurrentFuel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FuelRate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FuelRate)
        </dd>
    </dl>
</div>
<div>
    @if (User.HasClaim("Admin", bool.TrueString))
    {
        <div>

            <form asp-action="AddPictureToCar" asp-route-id="@Model.ID" asp-controller="PictureModels" method="post" enctype="multipart/form-data">
                <input type="file" name="uploadedFile" /><br>
                <input type="submit" value="Add Picture To Car" />
            </form>
        </div>
        <p></p>
        <div>
            <a asp-action="Edit" asp-route-id="@Model.ID" class="btn btn-danger">Изменить</a> |
            <a asp-action="Index" class="btn btn-secondary">Отмена</a>
        </div>
    }
    @if (User.HasClaim("Admin", bool.TrueString))
    {
        <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a>
    }
    <a asp-action="Index">Back to List</a>
</div>